import os
import json
import logging
import re
from typing import Optional, AsyncGenerator
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from emergentintegrations.llm.chat import LlmChat, UserMessage, TextDelta, StreamDone

logger = logging.getLogger("raahkar.ai")

class AIService:
    def __init__(self):
        self.api_key = os.environ.get("EMERGENT_LLM_KEY", "")
        self.base_url = os.environ.get("OPENAI_BASE_URL", "http://localhost:20128/v1")
        self.model = os.environ.get("OPENAI_MODEL", "cf/@cf/moonshotai/kimi-k2.5")

    def _get_chat_client(self, session_id: str, system_message: str):
        if not self.api_key:
            logger.warning("EMERGENT_LLM_KEY is missing. AI requests might fail.")
        return LlmChat(
            api_key=self.api_key,
            session_id=session_id,
            system_message=system_message,
            base_url=self.base_url,
        ).with_model("custom", self.model)

    async def stream_workflow_generation(self, session_id: str, message: str) -> AsyncGenerator[str, None]:
        from services.prompts import WORKFLOW_GENERATOR_PROMPT
        chat = self._get_chat_client(session_id, WORKFLOW_GENERATOR_PROMPT)
        
        async for ev in chat.stream_message(UserMessage(text=message)):
            if isinstance(ev, TextDelta):
                yield ev.content
            elif isinstance(ev, StreamDone):
                break

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
    async def ask_ai_json(self, session_id: str, system_prompt: str, user_message: str) -> dict:
        """
        Wrapper to strictly enforce JSON outputs from the LLM, with automatic retries on failure.
        Useful for Workflow AI Agent Nodes.
        """
        chat = self._get_chat_client(session_id, system_prompt)
        
        full_text = ""
        async for ev in chat.stream_message(UserMessage(text=user_message)):
            if isinstance(ev, TextDelta):
                full_text += ev.content
            elif isinstance(ev, StreamDone):
                break
                
        return self.extract_json_block(full_text)
        
    def extract_json_block(self, text: str) -> dict:
        m = re.search(r"```json\s*(\{.*?\})\s*```", text, re.DOTALL)
        if not m:
            m = re.search(r"(\{[\s\S]*\})", text)
            if not m:
                raise ValueError("No JSON block found in AI response")
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON generated by AI: {e}")

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
    async def extract_data_from_image(self, image_data: str, prompt: str) -> dict:
        """
        Uses Vision API capabilities to extract JSON data from an image.
        image_data can be a base64 data URI or a standard URL.
        """
        import httpx
        
        # Ensure it's formatted properly for OpenAI Vision API.
        if not image_data.startswith("http") and not image_data.startswith("data:image"):
            image_data = f"data:image/jpeg;base64,{image_data}"
            
        messages = [
            {"role": "system", "content": "You are a helpful data extraction AI. You MUST respond with ONLY valid JSON."},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {"url": image_data}
                    }
                ]
            }
        ]
        
        async with httpx.AsyncClient(timeout=120) as client:
            resp = await client.post(
                f"{self.base_url}/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": self.model,
                    "messages": messages,
                }
            )
            resp.raise_for_status()
            data = resp.json()
            full_text = data["choices"][0]["message"]["content"]
            
        return self.extract_json_block(full_text)

ai_service = AIService()
